# This is a basic workflow to help you get started with Actions

name: UleskaDemoAction

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -X GET "https://demo.uleska.com/SecureDesigner/api/v1/applications/c4994932-6d63-44f5-ab0d-fed18684864b/versions/62a4ab88-1691-42b3-8b19-eebac6bd7e04/scan" -H "accept: */*" -H "authorization: Basic Z2FyeS5yb2JpbnNvbkB1bGVza2EuY29tOkJvc3RvbjEyMw=="
